02 git rock paper scissors
Kernel-GL-HRK/gl-kernel-training-2019 pull request #6
Opened 2019-10-05 15:53 UTC by ChekanovSerhii

Develope game rock_paper_scissors, solution of my home work in  gl-kernel-training-2019.
Please review with my solution and if everything ok, allow me merging branches.

2019-10-07 11:40 UTC, an1kh requested changes
Please refactor (or add some commits) so the branch structure became e.g.:
1. dummy (getting choice from user) and makefile
2. random generation
3. comparison and winner determination

2019-10-07 11:40 UTC, an1kh commented on 02-Git/RockPaperScissors.sln
> +EndGlobal
Is this commit really needed?
If so, please include with the initial part of code

2019-10-09 14:34 UTC, SergeyChekanov commented on 02-Git/RockPaperScissors.sln
> +EndGlobal
Rewrited all pullrequest, this commit isn't needed. It have to be in all commits of feature.

2019-10-10 13:23 UTC, ChekanovSerhii commented
Dead branch

2019-10-10 13:23 UTC, closed without merging