05 interfaces procfs
Kernel-GL-HRK/gl-kernel-training-2019 pull request #73
Opened 2019-11-03 10:16 UTC by LinuxMod-dev

The simple procfs module

2019-11-04 07:44 UTC, an1kh requested changes
This will work, but not a good solution.
Better to have 2 separate file_operations, one RW for converter, and another RO for stats.
This will also eliminate the need to check paths every call.

2019-11-04 07:44 UTC, an1kh commented on 05-Interfaces/mymodule.c
> +	flog = proc_create(LOG_FILE_NAME, 0666, dir, &myops);
Should be read only

2019-11-04 07:57 UTC, LinuxMod-dev commented on 05-Interfaces/mymodule.c
> +	flog = proc_create(LOG_FILE_NAME, 0666, dir, &myops);
ok

2019-11-05 07:31 UTC, an1kh approved these changes
Please fix access rights and then merge without review.

2019-11-05 07:31 UTC, an1kh commented on 05-Interfaces/mymodule.c
> +	flog = proc_create(LOG_FILE_NAME, 0644, dir, &slog_ops);
Read-only for everyone 0444

2019-11-05 10:31 UTC, merged